site_name: MU-ty's Blog
site_url: https://mydomain.org/mysite

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: default    # 或 "friendly" / "colorful" 等浅色主题
      noclasses: true        # 使用内联样式，确保无需额外 CSS 即可看到高亮
      guess_lang: false
      anchor_linenums: true
      line_spans: "__span"
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
    - navigation.path

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
  - javascripts/katex-render.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MU-ty

plugins:
  - search

nav:
  - 首页: index.md  
  - LeetCode:
    - 介绍: leetcode/index.md
    - 哈希:
      - 0001.两数之和: leetcode/哈希/0001.两数之和.md
      - 0049.字母异位词分组: leetcode/哈希/0049. 字母异位词分组.md
      - 0128.最长连续序列: leetcode/哈希/0128. 最长连续序列.md
    - 双指针:
      - 0283.移动零: leetcode/双指针/0283. 移动零.md
      - 0011.盛最多水的容器: leetcode/双指针/0011.盛最多水的容器.md
      - 0015.三数之和: leetcode/双指针/0015.三数之和.md
      - 0042.接雨水: leetcode/双指针/0042.接雨水.md

    - 滑动窗口:
      - 1456.定长子串中元音的最大数目: leetcode/滑动窗口/1456. 定长子串中元音的最大数目.md
      - 643.子数组最大平均数Ⅰ: leetcode/滑动窗口/643. 子数组最大平均数 I.md
      - 1343.大小为K且平均值大于等于阈值的子数组数目: leetcode/滑动窗口/1343. 大小为 K 且平均值大于等于阈值的子数组数目.md
    - 链表:
      - 0160.相交链表: leetcode/链表/0160. 相交链表.md
      - 0206.反转链表: leetcode/链表/0206. 反转链表.md
      - 0876.链表的中间结点: leetcode/链表/0876.链表的中间结点.md
      - 0234.回文链表: leetcode/链表/0234.回文链表.md
      - 0141.环形链表Ⅰ: leetcode/链表/0141.环形链表Ⅰ.md
      - 0142.环形链表Ⅱ: leetcode/链表/0142. 环形链表 Ⅱ.md
      - 0021.合并两个有序链表: leetcode/链表/0021.合并两个有序链表.md
      - 0023.合并k个升序链表: leetcode/链表/0023.合并k个升序链表.md
      - 0002.两数相加: leetcode/链表/0002.两数相加.md
      - 0086.分隔链表: leetcode/链表/0086.分隔链表.md
      - 0019.删除链表的倒数第N个节点: leetcode/链表/0019.删除链表的倒数第N个结点.md

    - 二叉树:
      - 引入: leetcode/二叉树/引入.md

    - 二分查找:
      - 引入: leetcode/二分查找/引入.md
      - 0035_搜索插入位置: leetcode/二分查找/0035.搜索插入位置.md
      - 0074_搜索二维矩阵: leetcode/二分查找/0074.搜索二维矩阵.md
      - 0034_在排序数组中查找元素的第一个和最后一个位置: leetcode/二分查找/0034.在排序数组中查找元素的第一个和最后一个位置.md
      - 0033_搜索旋转排序数组: leetcode/二分查找/0033.搜索旋转排序数组.md
      - 0153_寻找旋转排序数组中的最小值: leetcode/二分查找/0153.寻找旋转排序数组中的最小值.md
      - 0004_寻找两个正序数组的中位数: leetcode/二分查找/0004.寻找两个正序数组的中位数.md
    - 栈:
      - 0020_有效的括号: leetcode/栈/0020.有效的括号.md
      - 0155_最小栈: leetcode/栈/0155.最小栈.md
      - Q1. 用栈操作构建数组: leetcode/栈/Q1. 用栈操作构建数组.md
      - Q2. 逆波兰表达式求值: leetcode/栈/Q2. 逆波兰表达式求值.md

      
    - 补充:
      - 二叉堆: leetcode/补充/二叉堆.md
      - 优先队列: leetcode/补充/优先队列.md
      - 树状数组: leetcode/补充/树状数组.md
      - 线段树: leetcode/补充/线段树.md
      - KMP算法: leetcode/补充/KMP算法.md
  

  # - Agent: Agent/index.md
  # - Backend: Backend/index.md
  - Deep Learning: 
    - Deep Learning/index.md
    - 1.线性代数基础: Deep Learning/1.线性代数.md
    - 2.概率统计基础: Deep Learning/2.概率统计.md
    - 3.导数、反向传播、复杂度: Deep Learning/3.导数、反向传播、复杂度.md
    - 4.线性方法、基础优化和 softmax 回归: Deep Learning/4.线性方法、基础优化和 softmax 回归.md
    - 5.最大似然估计 和 逻辑回归: Deep Learning/5.最大似然估计与逻辑回归.md
    - 6.多层感知机: Deep Learning/6.多层感知机.md
    - 7.模型选择，欠拟合与过拟合，权重衰减 和 丢弃法: Deep Learning/7.模型选择，欠拟合与过拟合，权重衰减 和 丢弃法.md
    - 阶段总结Ⅰ: Deep Learning/阶段总结Ⅰ.md
    - 8.前向传播、反向传播、计算图: Deep Learning/8.前向传播、反向传播、计算图.md
    - 9.数值稳定性、模型初始化: Deep Learning/9.数值稳定性、模型初始化.md
    - 10.环境、分布偏移: Deep Learning/10.环境、分布偏移.md
    - 11.深度学习计算: Deep Learning/11.深度学习计算.md
    - 12.卷积神经网络: Deep Learning/12.卷积神经网络.md
  # - Frontend: Frontend/index.md
  # - Python:
  #   - 第一章: python/第一章 python程序设计基础.md
  #   - 第二章: python/第二章 面向对象程序设计.md
  #   - 第三章: python/第三章 Python中的数据结构、模式匹配和算法理解.md
  # - CS168:
  #   - Home: CS168/home.md
  # - SAR:
  #   - glossary: SAR/glossary.md
  # - CS336:
  #   - Home: CS336/home.md
  - 更新日志: 
    - 更新日志: 更新日志/changelog.md
